const queueIdArray = [
  {
    queueId: 0,
    map: "Custom games",
    description: null,
    notes: null,
    title: "Custom",
  },
  {
    queueId: 72,
    map: "Howling Abyss",
    description: "1v1 Snowdown Showdown games",
    notes: null,
    title: "1v1 Snowdown Showdown",
  },
  {
    queueId: 73,
    map: "Howling Abyss",
    description: "2v2 Snowdown Showdown games",
    notes: null,
    title: "2v2 Snowdown Showdown",
  },
  {
    queueId: 75,
    map: "Summoner's Rift",
    description: "6v6 Hexakill games",
    notes: null,
    title: "Hexakill",
  },
  {
    queueId: 76,
    map: "Summoner's Rift",
    description: "Ultra Rapid Fire games",
    notes: null,
    title: "Ultra Rapid Fire",
  },
  {
    queueId: 78,
    map: "Howling Abyss",
    description: "One For All: Mirror Mode games",
    notes: null,
    title: "One For All (Mirror mode)",
  },
  {
    queueId: 83,
    map: "Summoner's Rift",
    description: "Co-op vs AI Ultra Rapid Fire games",
    notes: null,
    title: "Co-op vs AI Ultra Rapid Fire games",
  },
  {
    queueId: 98,
    map: "Twisted Treeline",
    description: "6v6 Hexakill games",
    notes: null,
    title: "Hexakill",
  },
  {
    queueId: 100,
    map: "Butcher's Bridge",
    description: "5v5 ARAM games",
    notes: null,
    title: "ARAM",
  },
  {
    queueId: 310,
    map: "Summoner's Rift",
    description: "Nemesis games",
    notes: null,
    title: "Nemesis",
  },
  {
    queueId: 313,
    map: "Summoner's Rift",
    description: "Black Market Brawlers games",
    notes: null,
    title: "Black Market Brawlers",
  },
  {
    queueId: 317,
    map: "Crystal Scar",
    description: "Definitely Not Dominion games",
    notes: null,
    title: "Definitely Not Dominion",
  },
  {
    queueId: 325,
    map: "Summoner's Rift",
    description: "All Random games",
    notes: null,
    title: "All Random",
  },
  {
    queueId: 400,
    map: "Summoner's Rift",
    description: "5v5 Draft Pick games",
    notes: null,
    title: "5v5 Draft Pick",
  },
  {
    queueId: 420,
    map: "Summoner's Rift",
    description: "5v5 Ranked Solo games",
    notes: null,
    title: "5v5 Ranked Solo",
  },
  {
    queueId: 430,
    map: "Summoner's Rift",
    description: "5v5 Blind Pick games",
    notes: null,
    title: "5v5 Blind Pick",
  },
  {
    queueId: 440,
    map: "Summoner's Rift",
    description: "5v5 Ranked Flex games",
    notes: null,
    title: "5v5 Ranked Flex",
  },
  {
    queueId: 450,
    map: "Howling Abyss",
    description: "5v5 ARAM games",
    notes: null,
    title: "5v5 ARAM",
  },
  {
    queueId: 490,
    map: "Summoner's Rift",
    description: "Normal (Quickplay)",
    notes: null,
    title: "Normal (Quickplay)",
  },
  {
    queueId: 600,
    map: "Summoner's Rift",
    description: "Blood Hunt Assassin games",
    notes: null,
    title: "Blood Hunt Assassin",
  },
  {
    queueId: 610,
    map: "Cosmic Ruins",
    description: "Dark Star: Singularity games",
    notes: null,
    title: "Dark Star: Singularity",
  },
  {
    queueId: 700,
    map: "Summoner's Rift",
    description: "Summoner's Rift Clash games",
    notes: null,
    title: "Clash",
  },
  {
    queueId: 720,
    map: "Howling Abyss",
    description: "ARAM Clash games",
    notes: null,
    title: "ARAM Clash",
  },
  {
    queueId: 820,
    map: "Twisted Treeline",
    description: "Co-op vs. AI Beginner Bot games",
    notes: null,
    title: "Beginner Bots",
  },
  {
    queueId: 830,
    map: "Summoner's Rift",
    description: "Co-op vs. AI Intro Bot games",
    notes: null,
    title: "Intro Bots",
  },
  {
    queueId: 840,
    map: "Summoner's Rift",
    description: "Co-op vs. AI Beginner Bot games",
    notes: null,
    title: "Begginer Bots",
  },
  {
    queueId: 850,
    map: "Summoner's Rift",
    description: "Co-op vs. AI Intermediate Bot games",
    notes: null,
    title: "Intermediate Bots",
  },
  {
    queueId: 900,
    map: "Summoner's Rift",
    description: "ARURF games",
    notes: null,
    title: "ARURF",
  },
  {
    queueId: 910,
    map: "Crystal Scar",
    description: "Ascension games",
    notes: null,
    title: "Ascension",
  },
  {
    queueId: 920,
    map: "Howling Abyss",
    description: "Legend of the Poro King games",
    notes: null,
    title: "Legend of the Poro King",
  },
  {
    queueId: 940,
    map: "Summoner's Rift",
    description: "Nexus Siege games",
    notes: null,
    title: "Nexus Siege",
  },
  {
    queueId: 950,
    map: "Summoner's Rift",
    description: "Doom Bots Voting games",
    notes: null,
    title: "Doom Bots",
  },
  {
    queueId: 960,
    map: "Summoner's Rift",
    description: "Doom Bots Standard games",
    notes: null,
    title: "Doom Bots",
  },
  {
    queueId: 980,
    map: "Valoran City Park",
    description: "Star Guardian Invasion: Normal games",
    notes: null,
    title: "Star Guardian Invasion: Normal",
  },
  {
    queueId: 990,
    map: "Valoran City Park",
    description: "Star Guardian Invasion: Onslaught games",
    notes: null,
  },
  {
    queueId: 1000,
    map: "Overcharge",
    description: "PROJECT: Hunters games",
    notes: null,
  },
  {
    queueId: 1010,
    map: "Summoner's Rift",
    description: "Snow ARURF games",
    notes: null,
  },
  {
    queueId: 1020,
    map: "Summoner's Rift",
    description: "One for All games",
    notes: null,
  },
  {
    queueId: 1030,
    map: "Crash Site",
    description: "Odyssey Extraction: Intro games",
    notes: null,
  },
  {
    queueId: 1040,
    map: "Crash Site",
    description: "Odyssey Extraction: Cadet games",
    notes: null,
  },
  {
    queueId: 1050,
    map: "Crash Site",
    description: "Odyssey Extraction: Crewmember games",
    notes: null,
  },
  {
    queueId: 1060,
    map: "Crash Site",
    description: "Odyssey Extraction: Captain games",
    notes: null,
  },
  {
    queueId: 1070,
    map: "Crash Site",
    description: "Odyssey Extraction: Onslaught games",
    notes: null,
  },
  {
    queueId: 1090,
    map: "Convergence",
    description: "Teamfight Tactics games",
    notes: null,
  },
  {
    queueId: 1100,
    map: "Convergence",
    description: "Ranked Teamfight Tactics games",
    notes: null,
  },
  {
    queueId: 1110,
    map: "Convergence",
    description: "Teamfight Tactics Tutorial games",
    notes: null,
  },
  {
    queueId: 1111,
    map: "Convergence",
    description: "Teamfight Tactics test games",
    notes: null,
  },
  {
    queueId: 1300,
    map: "Nexus Blitz",
    description: "Nexus Blitz games",
    notes: null,
  },
  {
    queueId: 1400,
    map: "Summoner's Rift",
    description: "Ultimate Spellbook games",
    notes: null,
  },
  {
    queueId: 1700,
    map: "Rings of Wrath",
    description: "Arena",
    notes: null,
    title: "Arena",
  },
  {
    queueId: 1900,
    map: "Summoner's Rift",
    description: "Pick URF games",
    notes: null,
  },
  {
    queueId: 2000,
    map: "Summoner's Rift",
    description: "Tutorial 1",
    notes: null,
  },
  {
    queueId: 2010,
    map: "Summoner's Rift",
    description: "Tutorial 2",
    notes: null,
  },
  {
    queueId: 2020,
    map: "Summoner's Rift",
    description: "Tutorial 3",
    notes: null,
  },
];

const getQueueIdData = (queueId: number) => {
  const queueIdData = queueIdArray.find((queue) => queue.queueId === queueId);
  return queueIdData?.title || "Unknown";
};

export default getQueueIdData;
